Deskewing
norlab-ulaval/norlab_icp_mapper_ros pull request #16
Opened 2024-12-26 03:08 UTC by boxanm

2025-01-05 21:05 UTC, simonpierredeschenes commented on src/Deskewer.cpp
> +    std::unordered_map<int64_t, int64_t> timeCache;
Why do you need the timeCache variable? This unordered_map seems to hold the value of `cloud.times(i) / deskewingRoundToNSecs`. I think that performing this operation every time you need this value would be faster than storing the result in a map and retriving it every time.

2025-01-05 21:13 UTC, simonpierredeschenes commented on src/NodeParameters.cpp
> +    node.declare_parameter<int>("expectedUniqueDeskewingTFNumber", 4000);
The new parameter names should be in snake_case to follow the current convention

2025-01-05 21:16 UTC, simonpierredeschenes commented on src/mapper_node.cpp
> +        inputFiltersScanPublisher = this->create_publisher<sensor_msgs::msg::PointCloud2>("scan_after_input_filters", 1);
The queue size is different for the two new publishers

2025-01-05 21:18 UTC, simonpierredeschenes commented on src/mapper_node.cpp
> +                if (deskewSuccessul)
There is a typo in successful

2025-01-05 21:22 UTC, simonpierredeschenes commented on src/mapper_node.cpp
> +        std::chrono::steady_clock::time_point begin1 = std::chrono::steady_clock::now();
`begin1` should be renamed to `processingStartTime`

2025-01-05 21:22 UTC, simonpierredeschenes commented on src/mapper_node.cpp
> +            std::chrono::steady_clock::time_point end = std::chrono::steady_clock::now();
`end` should be renamed to `filterEndTime`

2025-01-05 21:23 UTC, simonpierredeschenes commented on src/mapper_node.cpp
> +                std::chrono::steady_clock::time_point begin = std::chrono::steady_clock::now();
`begin` should be renamed to `mappingStartTime`

2025-01-05 21:24 UTC, simonpierredeschenes commented on src/mapper_node.cpp
> +                std::chrono::steady_clock::time_point end = std::chrono::steady_clock::now();
`end` should be renamed to `mappingEndTime`

2025-01-05 21:24 UTC, simonpierredeschenes commented on src/mapper_node.cpp
> +        std::chrono::steady_clock::time_point end1 = std::chrono::steady_clock::now();
`end1` should be renamed to `processingEndTime`

2025-01-05 21:28 UTC, simonpierredeschenes commented on src/mapper_node.cpp
> +            sensor_msgs::msg::PointCloud2 mapMsgOut = PointMatcher_ROS::pointMatcherCloudToRosMsg<float>(input, sensorFrame, timeStamp);
`mapMsgOut` should be renamed to filteredInputMsgOut

2025-01-05 21:29 UTC, simonpierredeschenes commented on src/mapper_node.cpp
> +            sensor_msgs::msg::PointCloud2 mapMsgOut = PointMatcher_ROS::pointMatcherCloudToRosMsg<float>(input, sensorFrame, timeStamp);
`mapMsgOut` should be renamed to `deskewedCloudMsgOut`

2025-01-05 21:30 UTC, simonpierredeschenes requested changes
Very good overall. There are a few minor changes to do, but the PR can be merged once they are done.

2025-01-05 22:57 UTC, boxanm commented on src/Deskewer.cpp
> +    std::unordered_map<int64_t, int64_t> timeCache;
You are right, this hash map is indeed unnecessary.

2025-01-06 03:27 UTC, simonpierredeschenes approved these changes

2025-01-28 02:34 UTC, merged